//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Break_Times
    {
        public int breakcheck { get; set; }
        public int BreakTimeID { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string Day { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public int Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
