//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_times
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string Status { get; set; }
        public string Day { get; set; }
        public int DailyTime_id { get; set; }
        public string Month { get; set; }
        public Nullable<int> check { get; set; }
    
        public virtual User User { get; set; }
    }
}
